---
#- name: Populate Apt's Cache with package definitions to avoid "no such package" errors
#  hosts: nodes
#  become: yes
#  tasks:
#    - name: Update apt cache
#      ansible.builtin.apt:
#        update_cache: yes
- name: install pip
  hosts: nodes
  become: yes
  gather_facts: true
  roles:
    - install_docker
    #  - bootstrap
    #- geerlingguy.docker
    #- { role: "geerlingguy.node_exporter", tags: "test" }
    #- geerlingguy.ntp
    #- geerlingguy.pip
    #- geerlingguy.postgresql
  #   - { role: "k3s", tags: "test2", become: yes }
  #   - oefenweb.locales
  #   - racqspace.unattended_upgrades
  #   - systemli.bind9
