proxy:
  hosts:
    185.149.45.175:

nodes:
  hosts:
    10.15.0.13:
      ansible_user: ubuntu
    #10.15.0.12:
    #  ansible_user: ubuntu
    #10.15.0.14:
    #  ansible_user: ubuntu

  vars:
    ansible_ssh_common_args: "-o ControlMaster=auto -o ControlPersist=5s -o ProxyJump=ubuntu@185.149.45.175"
